### ISSUE TITLE
Update stable version in repo from 0.1.0 to 0.3.0

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.welcome#15]
# Think about update stable version to 0.3.0
**Version**: stable=**0.1.0** (53 days old) => latest=**0.3.0** (30 days old)
**Installs**: stable=**501** (86.53%), latest=**73** (12.61%), total=**579**

Click to use [developer portal](https://www.iobroker.dev/adapter/welcome/releases)
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L2944)

Note: This is an automatically generated message and not personally authored by bluefox!

**Comment by mcm1957** [comment]
@GermanBluefox
@Apollon77

Is there any reason to delay updating stable any longer?
Please drop a commit if you know any reason to refrain from updating.

**If there is no response until 27.01.2024 we could decide to update anyway**

**Comment by GermanBluefox** [comment]
This issue seems to be outdated.

This issue suggests to update the stable version of this adapter to 0.3.0 but the current stable version is already 0.3.0.

So this issue should be closed.

@mcm1957 for evidence
